services:
  database:
    build: ./database-dump
    container_name: database_container
    ports: 
      - "27017:21017"
    environment:
      BACKEND_URL:

  backend:
    build: https://github.com/filiprank/trivia-backend.git
    # build: ./trivia-backend
    container_name: backend_container
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /app
    #       ignore: 
    #         - node_modules
    environment:
      GITHUB_CLIENT_ID: # Your Github OAuth client id
      GITHUB_CLIENT_SECRET: # Your Github OAuth client secret
      MONGO_URI: "mongodb://database:27017/trivia-app"
      FRONTEND_URL: "http://localhost:5173"
      
  frontend:
    build: https://github.com/filiprank/trivia-frontend.git
    # build: ./trivia-frontend
    container_name: frontend_container
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /app
    #       ignore: 
    #         - node_modules

networks:
  dockertry_default:
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"